<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Honeycomb.Application</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="ini-parser" Version="2.5.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\external\GH-Toolkit\GH-Toolkit-Core.csproj" />
  </ItemGroup>

</Project>
